force-app/main/default/objects/Demo_Reset_Task__c/Demo_Reset_Task__c.object-meta.xml
<CustomObject>
    <description>A specification for the deletion of an object&#39;s records as part of a demo reset.</description>
    <label>Demo Reset Task</label>
    <nameField>
        <displayFormat>DRT-{000}</displayFormat>
        <label>Demo Reset Task ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Reset Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/default/objects/Demo_Reset_Task__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A description of the demo reset item, for example, &quot;Delete all records that are not custom-crafted for the demo scenario&quot;.</description>
    <inlineHelpText>A description of the demo reset item, for example, &quot;Delete all records that are not custom-crafted for the demo scenario&quot;.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/default/objects/Demo_Reset_Task__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>API Name of the object whose records are to be deleted.</description>
    <inlineHelpText>API Name of the object whose records are to be deleted.</inlineHelpText>
    <label>Object API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DemoResetToolsTests.cls
@isTest 
public with sharing class DemoResetToolsTests {
    

    @isTest static void DemoResetToolsTests() {

        List<DemoResetTools.ResetTask> resetTasks = DemoResetTools.getResetTasks();
        System.assertEquals(null, resetTasks);

        List<DemoResetTools.Toast> toasts = DemoResetTools.demoReset(new List<Id>(), false);
        System.assertEquals(0, toasts.size());

        Demo_Reset_Task__c newResetTask = new Demo_Reset_Task__c();
        newResetTask.Active__c = true;
        newResetTask.Description__c = 'Delete all but Test User';
        newResetTask.Object_API_Name__c = 'Contact';
        newResetTask.SOQL_WHERE_Clause__c = 'FirstName = \'David\'';
        insert newResetTask;

        Contact newContact = new Contact();
        newContact.FirstName = 'John';
        newContact.LastName = 'Smith';
        newContact.Email = 'john.Smith.demo@mailinator.com';
        newContact.Phone = '5555555555';
        newContact.Title = 'Developer';      
        insert newContact;

        List<Id> badIdList = new List<Id>();
        badIdList.add(newContact.id);
        toasts = DemoResetTools.demoReset(badIdList, false);
        System.assertEquals(1, toasts.size());

        List<Id> idList = new List<Id>();
        idList.add(newResetTask.id);


        newContact = new Contact();
        newContact.FirstName = 'David';
        newContact.LastName = 'Smith';
        newContact.Email = 'David.Smith.demo@mailinator.com';
        newContact.Phone = '5555555555';
        newContact.Title = 'Developer';      
        insert newContact;

        resetTasks = DemoResetTools.getResetTasks();
        toasts = DemoResetTools.demoReset(idList, true);
        


        System.assertEquals(1, resetTasks.size());
        System.assertEquals(2, toasts.size());
    }



    @isTest static void DemoResetToolsDeleteTests() {

        Demo_Reset_Task__c newResetTask = new Demo_Reset_Task__c();
        
        newResetTask.Active__c = true;
        newResetTask.Description__c = 'Delete all but Test User';
        newResetTask.Object_API_Name__c = 'Contact';
        newResetTask.SOQL_WHERE_Clause__c = 'First_Name__c = \'David\'';

        insert newResetTask;
        
        List<Id> idList = new List<Id>();
        idList.add(newResetTask.id);

        List<DemoResetTools.Toast> toasts = DemoResetTools.demoReset(idList, true);
        
        Contact newContact = new Contact();
        
        newContact.FirstName = 'David';
        newContact.LastName = 'Smith';
        newContact.Email = 'david.larrimore.demo@mailinator.com';
        newContact.Phone = '5555555555';
        newContact.Title = 'Developer';      

        insert newContact;

        System.assertEquals(2, toasts.size());
    }    
}